w5e4 by Liron Farzam
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-lironfarzam pull request #3
Opened 2022-03-16 12:17 UTC by lironfarzam

2022-03-25 19:19 UTC, talbarfm commented
Give more detailed commit message

2022-03-25 19:19 UTC, talbarfm commented
Pick a different file name -  the w5e3 is a bad name - its not understandable to anyone but you

2022-03-25 19:48 UTC, talbarfm requested changes
Pay attention to read about existing implantations and libraries online before you go and implement something on your own, also pay attention to conventions - pep 8, documentation and variable names.

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +'''
""" not ''

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +def interleave(*iterable):
write the documents inside the function

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +def interleave(*iterable):
iterables* ?

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +    #Run like this on the loop because it is important that the first members of each list appear first
space after #

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +    j = 0
dont use single letter variables

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +    result = []
result? pick a meaningful name

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +    result = []
I want to enjoy reading the code, its supposed to be as close to English a possible

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +
Don't use imports in the middle of the file - separate to different files

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +        for i in range(len(iterable)):
try to reduce these for loops using one of these tools - map\filter\reduce\listcomprehention\itertools.chain\zip

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +# print(interleave('abc', [1, 2, 3], ('!', '@', '#', '$')))
???

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +# our_generator = interleave_generator('abc', [1, 2, 3], ('!', '@', '#', '$'))
Why do you have these comments inside the file?

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +The librarian who was on his way to bring me the coveted copy of "Harry Potter and the Rational Method" stumbled.
Im really hoping you didnt translate all of that on your own :) You dont have to do that

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +    if len(num) == 3:
https://stackoverflow.com/questions/3505831/in-python-how-do-i-convert-a-single-digit-number-into-a-double-digits-string - try to google search it

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +rename("Harry")
Add a newline at eof

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +    str=""
spaces around all operators

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +
Remove this newline

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +# function get string cut the head and split to num and title
Your functions should look like this -
![Capture](https://user-images.githubusercontent.com/13467749/160190790-be9aef6f-762b-46f5-b4f3-5dc5401dc5bb.JPG)

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +    while temp[i] != ":":
I would exclude each section to a different function - if you can define it as a section, you might as well give it a matching name

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +    i = 0
All of these variables should have better names

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +def getCapterNumAndTitel(str):
snake_case not camelCase

2022-03-25 19:48 UTC, talbarfm commented on w5e4.py
> +        file = codecs.open(path + "/" + filename, "r", encoding="utf8")
Change the names to better names in here as well

2022-03-31 18:21 UTC, lironfarzam commented on w5e4.py
> +'''
"""

2023-03-07 17:48 UTC, merged